# Q71. Write a program that can convert an integer to string.

In [1]:
def intToStr(num):
    return str(num) # convrting number to string

string = intToStr(20) # initializing the function
print(type(string)) # checking the type of the number which is string

<class 'str'>


# Q72. Write a program to print the shape of a matrix.

In [2]:
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]]

row = len(matrix) # number of row of matrix
column = len(matrix[0]) # number of column of matrix

print(f'shape of {matrix} is {row}x{column}')

shape of [[1, 2, 3], [4, 5, 6], [7, 8, 9]] is 3x3


# Q73. Write a program that can check if you can perform matrix multiplication on 2 matrices

In [3]:
import numpy as np
mat1 = np.array([[1,2,3],
                [4,5,6]])

mat2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

mat1_column = len(mat1[0]) # getting number of columns
mat2_row = len(mat2) # getting number of rows
if mat1_column == mat2_row: # checking if column of first matrix is equal to the row of second matrix
    print('matrix multiplication is possible')
else:
    print('matrix multiplication is not possible')

matrix multiplication is possible


# Q74. Write a program that can check if you can perform matrix multiplication on 2 matrices

In [4]:
import numpy as np # importing numpy library

mat1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
    
mat2 = np.array([[9,8,7],
                [6,5,4],
                [3,2,1]])

mat = np.zeros(shape=(3,3))
for i in range(3): # for row
    for j in range(3): # for column
        for k in range(3): # for adding
            mat[i][j] += mat1[i][k]*mat2[k][j] # adding the matrix in it row and columns position

print(mat)

[[ 30.  24.  18.]
 [ 84.  69.  54.]
 [138. 114.  90.]]


# Q75. Write a program that can sort a given unsorted list. Dont use any built in function for sorting.

In [5]:
lst = [6,8,4,9,8,2,7]
sorted_lst = []
for i in range(len(lst)-1): # iterating in a list starting from first to second last position
    for j in range(i+1, len(lst)): # iteratin in a list starting form second to last position
        if lst[j] < lst[i]: # checking if the first position is smaller than the rest of the list
            temp = lst[j] # if any number is smaller then it will come to the first position by swaping the postion
            lst[j] = lst[i] 
            lst[i] = temp

print(lst)

[2, 4, 6, 7, 8, 8, 9]


# Q76. Write a program that can find the most used word in a bollywood song

In [6]:
string = 'bollywood song'
dic = dict()
for i in string: # iterating through string
    if i in dic: # if the character is present in the dict then 
        dic[i] += 1 # increment the charcter by 1
    else:
        dic[i] = 1 # otherwise add the character and set it's value by 1

word = max(dic, key=dic.get) # getting the character with maximum number in dict
print(f'most used word in {string} is {word}')

most used word in bollywood song is o


# Q77. Assume a list with numbers from 1 to 10 and then convert it into a dictionary where the key would be the numbers of the list and the values would be the square of those numbers.

In [7]:
lst = [1,2,3,4,5,6,7,8,9,10]
dic = dict()
for i in lst:
    dic[i] = i**2 

print(dic)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


# Q78. Write a program to merge two given dictionary

In [8]:
dic1 = {'apples': 10, 'banana':12, 'oranges':15}
dic2 = {'mango':20, 'pineapple':5}
dic1.update(dic2) # adding dictionary 2 in dictionary 1
print(dic1)

{'apples': 10, 'banana': 12, 'oranges': 15, 'mango': 20, 'pineapple': 5}


# Q79. Write a program to swap the key value pair for max and min values
# Eg if the dict is like this {‘a’:1,’b’:2,’c’:3}
# Output should be {a:3,b:2,c:1}

In [9]:
dic =  {'a':1,'b':2,'c':3}
max_key = max(dic, key=dic.get) # getting the key whose value is maximum
min_key = min(dic, key=dic.get) # getting the key whose value is minimum
dic[min_key], dic[max_key] =  dic[max_key], dic[min_key] # swap the key with one another
print(dic)

{'a': 3, 'b': 2, 'c': 1}


# Q 80. Write a program to find histogram of a given set of numbers. Take bin size from user. Print the result in the form of a dictionary.

In [10]:
lst = [2,4,6,7,2,7,2,8,5,2,4,5,4,7,5,7,6,3,2,4,4,5,2,1,4,5,9,8,7,7,4,8,8,7]
bin = int(input('Enter a bin size: '))
start = min(lst)
last = max(lst)
bin_interval = (last-start)/bin  # size of the interval

interval_lst = [float(start)] # stores the list of interval values
hist = {}
j = start
for i in range(bin): 
    hist[f'{j:.1f}-{j+bin_interval:.1f}'] = 0 # creating the interval size
    j += bin_interval 
    interval_lst.append(float(round(j, 1))) # adding the interval in list

for i in lst:
    for j in range(len(interval_lst)):
        if j == 0:
            if i == interval_lst[j]: # checking if the value lies between the interval
                hist[f'{interval_lst[j]}-{interval_lst[j+1]}'] += 1 # incrementing the value if it lies in the given range
                break
        
        elif i <= interval_lst[j]:
            hist[f'{interval_lst[j-1]}-{interval_lst[j]}'] += 1
            break;


print(hist)


Enter a bin size: 5
{'1.0-2.6': 7, '2.6-4.2': 8, '4.2-5.8': 5, '5.8-7.4': 9, '7.4-9.0': 5}
