# Q71. Write a program that can convert an integer to string.

In [1]:
def intToStr(num):
    return str(num)

string = intToStr(20)
print(type(string))

<class 'str'>


# Q72. Write a program to print the shape of a matrix.

In [2]:
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]]

row = len(matrix)
column = len(matrix[0])

print(f'shape of {matrix} is {row}x{column}')

shape of [[1, 2, 3], [4, 5, 6], [7, 8, 9]] is 3x3


# Q73. Write a program that can check if you can perform matrix multiplication on 2 matrices

In [3]:
import numpy as np
mat1 = np.array([[1,2,3],
                [4,5,6]])

mat2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

mat1_column = len(mat1[0])
mat2_row = len(mat2)
if mat1_column == mat2_row:
    print('matrix multiplication is possible')
else:
    print('matrix multiplication is not possible')

matrix multiplication is possible


# Q74. Write a program that can check if you can perform matrix multiplication on 2 matrices

In [4]:
import numpy as np

mat1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
    
mat2 = np.array([[9,8,7],
                [6,5,4],
                [3,2,1]])

mat = np.zeros(shape=(3,3))
for i in range(3):
    for j in range(3):
        for k in range(3):
            mat[i][j] += mat1[i][k]*mat2[k][j]

print(mat)

[[ 30.  24.  18.]
 [ 84.  69.  54.]
 [138. 114.  90.]]


# Q75. Write a program that can sort a given unsorted list. Dont use any built in function for sorting.

In [5]:
lst = [6,8,4,9,8,2,7]
sorted_lst = []
for i in range(len(lst)-1):
    for j in range(i+1, len(lst)):
        if lst[j] < lst[i]:
            temp = lst[j]
            lst[j] = lst[i]
            lst[i] = temp

print(lst)

[2, 4, 6, 7, 8, 8, 9]
